stages:
  - check
  - baseline test
  - test
  - build
  - publish

check code smells:
  stage: check
  script:
    - merchise_lint
  tags:
    - merchise-lint
  allow_failure: true


check signature:
  stage: check
  script:
    - git verify-commit $CI_COMMIT_REF_NAME
  tags:
    - git
    - gpg
  only:
    - master


check signature of tag:
  stage: check
  script:
    - git verify-tag $CI_COMMIT_REF_NAME
  tags:
    - git
    - gpg
  only:
    - tags


run all tests in Python 2.7:
  stage: baseline test
  script: tox -e2.7
  tags:
    - python


run all tests in Python 3.6:
  stage: test
  script: tox -e3.6
  tags:
    - python3.6


build documentation:
  stage: build
  script:
    - mkdir -p envs
    - virtualenv envs/$CI_COMMIT_SHA
    - source envs/$CI_COMMIT_SHA/bin/activate
    - pip install sphinx sphinx-rtd-theme
    - pip install -e .
    - make -C docs/ html
    - cd docs/build/html
    - tar -cjf ../../../$CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 ./
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2
    expire_in: 4 days
  tags:
    - virtualenv
  only:
    - tags
    - master

publish in our rtd:
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - scp $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 rtd@docs.lahavane.com:.
    - ssh rtd@docs.lahavane.com mkdir -p $CI_PROJECT_NAME/.$CI_COMMIT_SHA
    - ssh rtd@docs.lahavane.com tar -xf $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 -C $CI_PROJECT_NAME/.$CI_COMMIT_SHA
    - ssh rtd@docs.lahavane.com "rm -r /var/www/html/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME; ln -sr /var/www/html/$CI_PROJECT_NAME/.$CI_COMMIT_SHA /var/www/html/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME"
    - ssh rtd@docs.lahavane.com rm $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2
    - ssh rtd@docs.lahavane.com "cd /var/www/html/$CI_PROJECT_NAME; ls -al | grep -oE '\.([0-9]|[a-z])*$' | sort | uniq -c | grep '1 ' | grep -oE '\.([0-9]|[a-z])*$' | xargs rm -rf"
  tags:
    - rtd@docs.lahavane.com
  dependencies:
    - build documentation
  environment:
    name: docs.lahavane.com
    url: http://docs.lahavane.com/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
  only:
    - tags
    - master
