stages:
  - check
  - baseline test
  - test
  - build
  - publish

check code smells:
  stage: check
  script:
    - merchise_lint
  tags:
    - merchise-lint
  allow_failure: true


check signature:
  stage: check
  script:
    - git verify-commit $CI_COMMIT_REF_NAME
  tags:
    - git
    - gpg
  only:
    - master


check signature of tag:
  stage: check
  script:
    - git verify-tag $CI_COMMIT_REF_NAME
  tags:
    - git
    - gpg
  only:
    - tags


run all tests in Python 2.7:
  stage: baseline test
  script: tox -e2.7
  tags:
    - python


run all tests in Python 3.6:
  stage: test
  script: tox -e3.6
  tags:
    - python3.6
