stages:
  - test
  - build
  - publish


run all tests in Python 2.7:
  stage: test
  script: tox -e2.7
  tags:
    - python

run all tests in Python 3.6:
  stage: test
  script: tox -e3.6
  tags:
    - python3.6
